option(ADB_STUDIO_BUILD_TESTS "Build ADB Studio tests" ON)
option(ADB_STUDIO_WARNINGS_AS_ERRORS "Treat first-party warnings as errors" ON)
option(ADB_STUDIO_ENABLE_SANITIZERS "Enable Clang sanitizers" OFF)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_AUTOMOC ON)

if(MSVC)
  add_compile_options(/W4 /permissive- /EHsc /utf-8)
  add_compile_options($<$<CONFIG:Release>:/Zi>)
  add_link_options($<$<CONFIG:Release>:/DEBUG:FULL> $<$<CONFIG:Release>:/OPT:REF>
                   $<$<CONFIG:Release>:/OPT:ICF>)
  if(ADB_STUDIO_WARNINGS_AS_ERRORS)
    add_compile_options(/WX)
  endif()
else()
  add_compile_options(-Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion)
  if(ADB_STUDIO_WARNINGS_AS_ERRORS)
    add_compile_options(-Werror)
  endif()
endif()

if(ADB_STUDIO_ENABLE_SANITIZERS AND CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
  add_compile_options(-fsanitize=address,undefined -fno-omit-frame-pointer)
  add_link_options(-fsanitize=address,undefined)
endif()
