name: Documentation
on: { pull_request: {}, workflow_dispatch: {} }
jobs:
  windows:
    uses: ./.github/workflows/_windows.yml
    with: { configuration: Debug, artifact-name: documentation-validation }
