name: Release Validation
on: { pull_request: {}, workflow_dispatch: {}, workflow_call: {} }
jobs:
  windows:
    uses: ./.github/workflows/_windows.yml
    with: { configuration: Release, artifact-name: release-validation, command: package }
